/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import forms.phases.ActivePressure;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author desti
 */
public class Dashboard extends javax.swing.JFrame {
    
    /**
     * Declare all needed variables for computation
     * Pa - Active Pressure, PA - Earth Force, Ka - 
     */
    private int phiVal, lambdaVal;
    private double Ka, Pa, PA;
    public int FCU = 24;
    public int B = 1;
    public double Ps, q, h1, h2, a1, a2, a3, a4, a5, H, L, b, W, E, γ, μ;
    public double THL, TVL, S_FOS, O_FOS, S, P1, P2, M, RM, OM;
    NumberFormat formatter = new DecimalFormat("#0.00");

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        initComponents();
        lblFCU.setText(String.valueOf(FCU));        
        lblB.setText(String.valueOf(B));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtPhi = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtH_Input = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtL_input = new javax.swing.JTextField();
        txtH1_Input = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtH2_input = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtA1_input = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtA3_Input = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtA4_Input = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtQ_Input = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtU_input = new javax.swing.JTextField();
        lblFCU = new javax.swing.JLabel();
        txtY_Input = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        btnChangeFCU = new javax.swing.JButton();
        btnCalculateResult = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        lblB = new javax.swing.JLabel();
        btnChangeB = new javax.swing.JButton();
        btnResetForm = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        lblResult = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        lblPa = new javax.swing.JLabel();
        lblPA = new javax.swing.JLabel();
        lblSurcharge = new javax.swing.JLabel();
        lblTHL = new javax.swing.JLabel();
        lblTVL = new javax.swing.JLabel();
        lblOM = new javax.swing.JLabel();
        lblRM = new javax.swing.JLabel();
        lblM = new javax.swing.JLabel();
        lblP1 = new javax.swing.JLabel();
        lblP2 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        btnImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dashboard");
        setBackground(new java.awt.Color(255, 204, 204));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(255, 204, 204));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel4.setText("Enter Value for Phi (Ø)");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, -1, -1));
        jPanel3.add(txtPhi, new org.netbeans.lib.awtextra.AbsoluteConstraints(343, 45, 290, 45));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setText("Overall Height of Wall (H)");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 106, -1, -1));
        jPanel3.add(txtH_Input, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 135, 305, 45));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel5.setText("Overall Lenght of Base (L)");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, -1, -1));
        jPanel3.add(txtL_input, new org.netbeans.lib.awtextra.AbsoluteConstraints(338, 135, 290, 45));
        jPanel3.add(txtH1_Input, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 305, 45));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel6.setText("Hieght of Wall (h1)");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel7.setText("Height of Base (h2)");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 190, -1, -1));
        jPanel3.add(txtH2_input, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, 290, 45));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel8.setText("Width of Wall (a1)");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, -1));
        jPanel3.add(txtA1_input, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 305, 45));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel9.setText("Length of Toe (a3)");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 280, -1, -1));
        jPanel3.add(txtA3_Input, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 310, 290, 45));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel10.setText("Length of Heel (a4)");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, -1, -1));
        jPanel3.add(txtA4_Input, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 305, 45));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel11.setText("Load of Surcharge (q)");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 370, -1, -1));
        jPanel3.add(txtQ_Input, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 400, 290, 45));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel12.setText("Coefficient of Friction (μ)");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, -1, -1));
        jPanel3.add(txtU_input, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, 305, 45));

        lblFCU.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblFCU.setText("0");
        jPanel3.add(lblFCU, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 560, -1, -1));
        jPanel3.add(txtY_Input, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 300, 45));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel14.setText("Bulk Density of Soil (γ)");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 200, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel15.setText("FCU is given as : ");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 560, -1, -1));

        btnChangeFCU.setText("Change");
        btnChangeFCU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeFCUActionPerformed(evt);
            }
        });
        jPanel3.add(btnChangeFCU, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 560, -1, -1));

        btnCalculateResult.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnCalculateResult.setText("Calculate Result");
        btnCalculateResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculateResultActionPerformed(evt);
            }
        });
        jPanel3.add(btnCalculateResult, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 600, -1, 50));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel16.setText("Unit Width (B) is given as : ");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 610, -1, -1));

        lblB.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblB.setText("0");
        jPanel3.add(lblB, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 610, -1, -1));

        btnChangeB.setText("Change");
        btnChangeB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeBActionPerformed(evt);
            }
        });
        jPanel3.add(btnChangeB, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 610, -1, -1));

        btnResetForm.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnResetForm.setText("Reset Form");
        btnResetForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetFormActionPerformed(evt);
            }
        });
        jPanel3.add(btnResetForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 540, 180, 50));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 644, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 676, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 204, 204));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel13.setText("Result:");

        lblResult.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblResult.setText("0");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblResult)
                .addContainerGap(855, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(lblResult))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setText("DETAILED ANALYSIS:");

        lblPa.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblPa.setText("Active Pressure (Pa):  ");

        lblPA.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblPA.setText("Earth Force (PA): ");

        lblSurcharge.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblSurcharge.setText("Surcharge: ");

        lblTHL.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTHL.setText("Total Horizontal Load (THL): ");

        lblTVL.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTVL.setText("Total Vertical Load (TVL): ");

        lblOM.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblOM.setText("Overturning Moment (OM): ");

        lblRM.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblRM.setText("Resisting Moment (RM): ");

        lblM.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblM.setText("Moment (M): ");

        lblP1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblP1.setText("Earth Pressure (P1):  ");

        lblP2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblP2.setText("Earth Pressure (P2):  ");

        btnImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/rt_wall2.jpg"))); // NOI18N
        btnImage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnImageMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnImage, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 16, Short.MAX_VALUE)
                .addComponent(btnImage, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTHL)
                            .addComponent(lblTVL)
                            .addComponent(lblOM)
                            .addComponent(lblRM)
                            .addComponent(lblM)
                            .addComponent(lblP1)
                            .addComponent(lblP2)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblPA)
                                    .addComponent(lblSurcharge)
                                    .addComponent(lblPa)
                                    .addComponent(jLabel17))
                                .addGap(293, 293, 293)
                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(160, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)
                        .addComponent(jLabel17)
                        .addGap(30, 30, 30)
                        .addComponent(lblPa)
                        .addGap(44, 44, 44))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(lblPA)
                .addGap(30, 30, 30)
                .addComponent(lblSurcharge)
                .addGap(42, 42, 42)
                .addComponent(lblTHL)
                .addGap(30, 30, 30)
                .addComponent(lblTVL)
                .addGap(30, 30, 30)
                .addComponent(lblRM)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblOM)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblM)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblP1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblP2)
                .addContainerGap(843, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(588, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(1777, 1019));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnChangeFCUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeFCUActionPerformed
        String fcu = JOptionPane.showInputDialog("Enter the value for FCU");
        lblFCU.setText(fcu);
        FCU = Integer.parseInt(fcu);
    }//GEN-LAST:event_btnChangeFCUActionPerformed

    private void btnCalculateResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculateResultActionPerformed
        try {
            // Accept all input values into their correspoding variables
            phiVal = Integer.parseInt(txtPhi.getText());
            H = Double.parseDouble(txtH_Input.getText());
            h1 = Double.parseDouble(txtH1_Input.getText());
            h2 = Double.parseDouble(txtH2_input.getText());
            a1 = Double.parseDouble(txtA1_input.getText());
            a3 = Double.parseDouble(txtA3_Input.getText());
            a4 = Double.parseDouble(txtA4_Input.getText());
            L = Double.parseDouble(txtL_input.getText());
            μ = Double.parseDouble(txtU_input.getText());
            γ = Double.parseDouble(txtY_Input.getText());
            q = Double.parseDouble(txtQ_Input.getText());

            // Calculate and display Active Pressure
            // Convert PHI val to redian
            double phi = phiVal * (Math.PI / 180);
            Ka = (1 - Math.sin(phi)) / (1 + Math.sin(phi));
            Pa = Ka * γ * H;
            lblPa.setText(lblPa.getText() + " " + formatter.format(Pa)+ " KN/M");

            // Calculate and display Earth Force
            PA = Pa * H * 0.5;
            lblPA.setText(lblPA.getText() + " " + formatter.format(PA)+ " KN");

            // Calculate a2 and a5
            a2 = (0.5 * a1) + a3;
            a5 = a1 + a3 + (0.5 * a4);

            // Calculate and display Surcharge
            Ps = Ka * q * H;
            lblSurcharge.setText(lblSurcharge.getText() + " " + formatter.format(Ps) + " KN/M");

            // Calculate and Display Total Horizontal Load (THL)
            THL = Ps + PA;
            lblTHL.setText(lblTHL.getText() + " " + formatter.format(THL)+ " KN");

            // Calculate and Display Total Vertical Load (TVL)
            // First, Calculating wall (W)
            W = a1 * h1 * FCU;
            // Secondly, Calculating Earth
            E = h1 * a4 * γ;
            // Thirdly, Calculating the base (b)
            b = h2 * L * FCU;
            // Finally, Calculating the TVL
            TVL = W + b + E;
            lblTVL.setText(lblTVL.getText() + " " + formatter.format(TVL)+ " KN");

            // Checking Stability
            // First, Calculate sliding
            S = μ * (1.0 * TVL);
            // μ * (1.0 * TVL) >= (1.6 * THL);

            // Second Step, Sliding FOS
            double RF = (μ * TVL);
            double SF = THL;
            S_FOS = RF / SF;

            // Check if the S_FOS is less than 1.6
            if(S_FOS < 1.6){
                JOptionPane.showMessageDialog(rootPane, "Retaining Wall Not Safe against Sliding. Factor of saftey is less than 1.6.");
            }

            // Third step is to check for overturning moment,OM
            double EM = PA * (H/3);
            double SM = Ps * (H/2);
            OM = EM + SM;
            lblOM.setText(lblOM.getText() + " " + formatter.format(OM)+ " KN/M");

            // Fourth Step is to Check for Resisting Moment
            double WRM = W * a2;
            double BRM = b * (0.5 * L);
            double ERM = E * a5;
            RM = WRM + BRM + ERM;
            lblRM.setText(lblRM.getText() + " " + formatter.format(RM)+ " KN/M");

            // Overturning moment FOS
            O_FOS = (RM / OM);

            // Check if the O_FOS is less 2.0
            if(O_FOS < 2.0){
                JOptionPane.showMessageDialog(rootPane, "Retaining Wall Not Safe. Overturning Moment's Factor of saftey is less than 2.0");
            }

            // Calculating Moment using Clockwise Moment(CM) and Counter Clockwise(CCM)
            double CM = E * (a5 - (0.5 * L));
            double CCM = (PA * 2.0) + (Ps * 3.0) + (W * ((0.5 * L) - a2));
            M = CCM - CM;
            System.out.println("CM = " + CM);
            System.out.println("CCM = " + CCM);
            lblM.setText(lblM.getText() + " " + formatter.format(M)+ " KN/M");


            // Calculating Earth Pressure (P)
            P1 = (TVL / (B * L)) + ((6 * M) / (B * Math.pow(L, 2)));
            P2 = (TVL / (B * L)) - ((6 * M) / (B * Math.pow(L, 2)));
            lblP1.setText(lblP1.getText() + " " + formatter.format(P1)+ " KN/M");
            lblP2.setText(lblP2.getText() + " " + formatter.format(P2)+ " KN/M");
            lblResult.setText(formatter.format(P1) + " KN/M or " + formatter.format(P2)+ " KN/M");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Invalid or Missing Data! Kindly make sure all input were entered correctly.");
        }
    }//GEN-LAST:event_btnCalculateResultActionPerformed

    private void btnChangeBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeBActionPerformed
        String b = JOptionPane.showInputDialog("Enter the value for Unit Width (B)");
        lblB.setText(b);
        B = Integer.parseInt(b);
    }//GEN-LAST:event_btnChangeBActionPerformed

    private void btnResetFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetFormActionPerformed
        lblResult.setText("0");
        lblP2.setText("Earth Pressure (P2):  ");
        lblP1.setText("Earth Pressure (P1):  ");
        lblM.setText("Moment (M): ");
        lblRM.setText("Resisting Moment (RM): ");
        lblOM.setText("Overturning Moment (OM): ");
        lblTVL.setText("Total Vertical Load (TVL): ");
        lblTHL.setText("Total Horizontal Load (THL): ");
        lblSurcharge.setText("Surcharge: ");
        lblPA.setText("Earth Force (PA): ");
        lblPa.setText("Active Pressure (Pa):  ");
        
        // Clear Input boxes as well
        txtH_Input.setText("");
        txtH1_Input.setText("");
        txtH2_input.setText("");
        txtA1_input.setText("");
        txtA3_Input.setText("");
        txtA4_Input.setText("");
        txtL_input.setText("");
        txtU_input.setText("");
        txtY_Input.setText("");
        txtQ_Input.setText("");
        txtPhi.setText("");
    }//GEN-LAST:event_btnResetFormActionPerformed

    private void btnImageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnImageMouseClicked
        new ImageViewer(this, true).show(true);
    }//GEN-LAST:event_btnImageMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalculateResult;
    private javax.swing.JButton btnChangeB;
    private javax.swing.JButton btnChangeFCU;
    private javax.swing.JLabel btnImage;
    private javax.swing.JButton btnResetForm;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel lblB;
    private javax.swing.JLabel lblFCU;
    private javax.swing.JLabel lblM;
    private javax.swing.JLabel lblOM;
    private javax.swing.JLabel lblP1;
    private javax.swing.JLabel lblP2;
    private javax.swing.JLabel lblPA;
    private javax.swing.JLabel lblPa;
    private javax.swing.JLabel lblRM;
    private javax.swing.JLabel lblResult;
    private javax.swing.JLabel lblSurcharge;
    private javax.swing.JLabel lblTHL;
    private javax.swing.JLabel lblTVL;
    private javax.swing.JTextField txtA1_input;
    private javax.swing.JTextField txtA3_Input;
    private javax.swing.JTextField txtA4_Input;
    private javax.swing.JTextField txtH1_Input;
    private javax.swing.JTextField txtH2_input;
    private javax.swing.JTextField txtH_Input;
    private javax.swing.JTextField txtL_input;
    private javax.swing.JTextField txtPhi;
    private javax.swing.JTextField txtQ_Input;
    private javax.swing.JTextField txtU_input;
    private javax.swing.JTextField txtY_Input;
    // End of variables declaration//GEN-END:variables
}
